export const UPDATE_Q453 = 'UPDATE_Q453'
export const UPDATE_Q1279 = 'UPDATE_1279'

export const ADD_RESPONSE = "ADD_RESPONSE"
export const RESET_RESPONSES = "RESET_RESPONSES"
export const FETCH_QUESTIONS = "FETCH_QUESTIONS"
export const QUESTIONS_LOADING = "QUESTIONS_LOADING"
export const RESET_STORE = "RESET_STORE"
export const RESPONSE_LOADING = "RESPONSE_LOADING"
export const SET_SERVICE_DETAILS = "SET_SERVICE_DETAILS"